redis:
  host: redis-16438.c282.east-us-mz.azure.cloud.redislabs.com
  db: 0
  user: default
  password: lckrJBwzK0CmXRIgE6sRbjoEXBENAzDD
  port: 16438

API:
  JSON_placeholder:
    url: https://jsonplaceholder.typicode.com/users
    index: 1

  TV:
    url: http://api.tvmaze.com/singlesearch/shows
    params: {"q":"Friends"}
    index: TV_show:1
  
  Crime: 
    url: https://jgentes-crime-data-v1.p.rapidapi.com/crime
    params: {"startdate": "9/19/2015", "enddate": '9/25/2015', "long": "-122.5076392", "lat": "37.757815"}
    headers: { "X-RapidAPI-Key": "a0dd196a09mshcacea72b440d8e9p15578ajsnb703b6903e99", "X-RapidAPI-Host": "jgentes-Crime-Data-v1.p.rapidapi.com"}

  SEC_filings: 
    url: https://apidojo-yahoo-finance-v1.p.rapidapi.com/stock/get-sec-filings
    querystring: {"symbol":"AMRN","region":"US","lang":"en-US"}
    headers: {"X-RapidAPI-Key": "a0dd196a09mshcacea72b440d8e9p15578ajsnb703b6903e99", "X-RapidAPI-Host": "apidojo-yahoo-finance-v1.p.rapidapi.com"}
    index: SEC_filings_api_result:1
